### ISSUE TITLE
can't find libleveldb when compiling on debian

### ISSUE THREAD

**Issue by denis-b** [pantheon-systems/fusedav#185]
Hi, i'm trying to compile on debian wheezy, and i got an error :  

checking for LEVELDB... no
configure: error: Package requirements ( leveldb ) were not met:

No package 'leveldb' found

The package is installed, backported from debian testing : 

# apt-cache show libleveldb-dev
Package: libleveldb-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 816
Maintainer: Alessio Treglia <alessio@debian.org>
Architecture: amd64
Multi-Arch: same
Source: leveldb
Version: 1.15.0-1~bpo70+1
Depends: libleveldb1 (= 1.15.0-1~bpo70+1)
Suggests: leveldb-doc
Description-en: fast key-value storage library (development files)
 LevelDB is a fast key-value storage library written at Google that
 provides an ordered mapping from string keys to string values.
 .
 This package provides the development files.
Homepage: http://code.google.com/p/leveldb/

# apt-cache show libleveldb1
Package: libleveldb1
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 363
Maintainer: Alessio Treglia <alessio@debian.org>
Architecture: amd64
Multi-Arch: same
Source: leveldb
Version: 1.15.0-1~bpo70+1
Depends: libc6 (>= 2.4), libgcc1 (>= 1:4.1.1), libsnappy1, libstdc++6 (>= 4.1.1)
Pre-Depends: multiarch-support
Description-en: fast key-value storage library
 LevelDB is a fast key-value storage library written at Google that
 provides an ordered mapping from string keys to string values.
 .

**Comment by ZuBB** [comment]
same thing here :(

**Comment by krlmlr** [comment]
Same here. Had to install `libjemalloc-dev libexpat-dev libsystemd-journal-dev` before arriving there. A list of nonusual prerequisites in the README would be great.

**Comment by davidstrauss** [comment]
Is LevelDB packaged on Debian?

**Comment by krlmlr** [comment]
@davidstrauss: Yes, see original comment: https://github.com/pantheon-systems/fusedav/issues/185#issue-30916216

**Comment by nstielau** [comment]
Hey @denis-b @ZuBB @krlmlr,

Thanks for your interest and report.  Right now, we're not prepared to support fusedav beyond our specific use-case (Fedora 20, Fedora 22) at present.  Closing out for now.

-Nick

**Comment by filipslavik** [comment]
Hi, 

One way to compile fusedav under current stable Debian is by installing at least the following packages 

```
zlib1g-dev liburiparser-dev libcurl4-openssl-dev libleveldb-dev
libglib2.0-0 libglib2.0-dev fuse autoconf libfuse-dev libjemalloc-dev 
build-essential git libsystemd-journal-dev pkg-config pkgconf libexpat1-dev
```

Remember, to run the ``configure`` command as shown bellow :
```
LEVELDB_LIBS='-L/usr/lib -lleveldb' LEVELDB_CFLAGS='-I/usr/include' ./configure
```

For me, it did the trick :-)
