### ISSUE TITLE
open with O_CREAT in second argument needs 3 arguments

### ISSUE THREAD

**Issue by gdamjan** [pantheon-systems/fusedav#204]
Compiling on Arch with gcc-5.1 and glibc 2.21 I get this error:

    In file included from /usr/include/fcntl.h:302:0,
                 from /usr/include/fuse/fuse.h:28,
                 from stats.c:23:
    In function ‘open’,
        inlined from ‘dump_stats’ at stats.c:145:12: 
    /usr/include/bits/fcntl2.h:50:4: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT in second argument needs 3 arguments
        __open_missing_mode ();

The fix is to add a mode to the open call in stats.c on line 145

    -        fd = open(stat_path, O_CREAT | O_WRONLY | O_TRUNC);
    +        fd = open(stat_path, O_CREAT | O_WRONLY | O_TRUNC, 0600);

**Comment by jerryblakley** [comment]
Thanks for the note. This fix will go in with the next update in the next few days.

**Comment by jerryblakley** [comment]
This fix is now in on the master and production branches.
Thanks for the tip.

**Comment by jerryblakley** [comment]
This fix is now on the master and production branches.
Thanks for the tip.

On Tue, Jun 2, 2015 at 1:43 AM, Дамјан Георгиевски <notifications@github.com
> wrote:

> Compiling on Arch with gcc-5.1 and glibc 2.21 I get this error:
>
> In file included from /usr/include/fcntl.h:302:0,
>              from /usr/include/fuse/fuse.h:28,
>              from stats.c:23:
> In function ‘open’,
>     inlined from ‘dump_stats’ at stats.c:145:12:
> /usr/include/bits/fcntl2.h:50:4: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT in second argument needs 3 arguments
>     __open_missing_mode ();
>
> The fix is to add a mode to the open call in stats.c on line 145
>
> -        fd = open(stat_path, O_CREAT | O_WRONLY | O_TRUNC);
> +        fd = open(stat_path, O_CREAT | O_WRONLY | O_TRUNC, 0600);
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pantheon-systems/fusedav/issues/204>.
>



-- 
Jerry Blakley
Senior Systems Engineer | Pantheon
jerry@pantheon.io
