### ISSUE TITLE
fusedav silently quits

### ISSUE THREAD

**Issue by klaszlo** [pantheon-systems/fusedav#241]
Hi,

I compiled fusedav, but it silently quits to all commandline options, except -h, -V.
    
    l@lolza:~/down/fusedav/src$ ./fusedav -V
    fusedav version 2.0.ee02367
    LevelDB version 1.17
    libcurl/7.37.1 GnuTLS/3.2.16 zlib/1.2.8 libidn/1.28 librtmp/2.3
    FUSE library version: 2.9.2
    fusermount version: 2.9.2
    using FUSE kernel interface version 7.19
    l@lolza:~/down/fusedav/src$ 

This is how I try to connect to the remote server (which works with original (system bundled) fusedav):

    l@lolza:~/down/fusedav/src$ ./fusedav -u admin -p mypasswoRd12 https://my2.mtoolsde.com:5002 /mnt/mtoolsde
    l@lolza:~/down/fusedav/src$ 

I tired option `-d`, `-f`, but the same issue. It just gives back the command line after 4 seconds.

(but with the original fusedav client I get the error 405 PROPFIND method not allowed error message.
With nautilus I can connect with admin user, but not with 'INTRA\accountant' user. I tried a couple of other clients, but each of it has its own error. This project looks the most matured one)

Looking with wireshark, there is no packet going toward the remote server.
I would like to use the username 'INTRA\accountant' on the remote server. 

Maybe I miss something obvious?
I'm on ubuntu system 15.04. I installed all dependency as detailed in this issue (last comment):
https://github.com/pantheon-systems/fusedav/issues/185

Any idea?

**Comment by jerryblakley** [comment]
Thanks for your note. Unfortunately we are unable to provide assistance.
